################################### Default Configuration ############################
baseurl = "https://2026.pass-the-salt.org/"
title = "Pass the SALT 2026"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
# googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Remove tags and categories page ##################
# https://gohugo.io/content-management/taxonomies/
# disableKinds did not seem to work but empty taxonomy does
[taxonomies]

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
# [[params.plugins.css]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "About"
url = "https://2026.pass-the-salt.org/#description"
weight = 10



# [[menu.main]]
# name = "Schedule"
# url = "https://cfp.pass-the-salt.org/pts2025/schedule/"
# weight = 20

#[[menu.main]]
#name = "Register"
#url = "https://pretix.eu/passthesalt/2025/"
#weight = 3

[[menu.main]]
name = "Memories"
url = "https://archives.pass-the-salt.org/Pass%20the%20SALT/2025/photos/PhotosPassTheSALT2025-by-jlm/"
weight = 30

# [[menu.main]]
# name = "Slides"
# url = "https://archives.pass-the-salt.org/Pass%20the%20SALT/2025/slides/"
# weight = 31

# [[menu.main]]
# name = "Videos"
# url = "https://passthesalt.ubicast.tv/channels/#2025"
# weight = 32

[[menu.main]]
name = "Practical"
url = "/practical/"
weight = 41

# [[menu.main]]
# name = "Report"
# url = "/annual-report/"
# weight = 42

[[menu.main]]
name = "Sponsors"
url = "/#sponsors"
weight = 50

[[menu.main]]
name = "CoC"
url = "/code-of-conduct/"
weight = 60

[[menu.main]]
name = "Archives"
url = "https://www.pass-the-salt.org/archives/"
weight = 70

# [[menu.main]]
# name = "Contact"
# url = "contact/"
# weight = 5

# footer menu
# [[menu.footer]]
# name = "Blog"
# url = "blog/"
# weight = 1

# [[menu.footer]]
# name = "Contact"
# url = "contact/"
# weight = 2

[[menu.footer]]
name = "Contact"
url = "mailto:contact@pass-the-salt.org"
weight = 1

[[menu.footer]]
name = "Mastodon"
url = "https://infosec.exchange/@passthesaltcon"
weight = 2

[[menu.footer]]
name = "X / Twitter"
url = "https://twitter.com/passthesaltcon"
weight = 3

# [[menu.footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 4


########################### Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "103px"
# Meta data
description = "Website of the 2026 edition of the Pass the SALT conference"
author = "Themefisher"
# currency
# currency = "$"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Snipcart
[params.snipcart]
enable = false
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Powered by [Hugo](https://gohugo.io/) | Theme Vex by [Themefisher](https://themefisher.com/)+[Gethugothemes](https://gethugothemes.com/) | Tuned by [@passthesaltcon](https://infosec.exchange/@passthesaltcon/)."


################################### French language #####################################
# [Languages.fr]
# languageName = "Fr"
# languageCode = "fr-fr"
# contentDir = "content/french"
# weight = 2
# copyright
# copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
